name: terraform automation to create ec2

on:
 pull_request:
   branches:
    - main
 push:    
   paths: 
    - 'terraform/**'
  
 workflow_dispatch:
 
 

permissions:
 id-token: write
 contents: write

jobs:
  terraform_s3_builb:
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: ./terraform

   steps:
     - name: checkout repository
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: configure the aws credentials
       uses: aws-actions/configure-aws-credentials@v4.1.0
       with:
         aws-region: ap-south-1
         role-to-assume: ${{secrets.OIDC_TOKEN_GITHUB}}
         
         

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.4.1
 
     - name: Terraform plan
       id: plan
       run: terraform plan

     - name: Terraform Apply
       run: terraform apply -auto-approve -input=false       

      
