name: Terraform CI with Sentinel

on:
  pull_request:
    branches: [ main ]

env:
  TF_CLOUD_ORGANIZATION: "cloud-devops-vin"
  TF_WORKSPACE: "terraform-to-test-sentinel-policy"

jobs:
  terraform-speculative-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color
