name: terraform automation to create ec2

on:
 pull_request:
   branches:
    - master
 push:    
   paths: 
    - 'terraform/**'
  
 workflow_dispatch:
 
 

permissions:
 id-token: write
 contents: write

jobs:
  terraform_s3_builb:
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: ./terraform

   steps:
     - name: checkout repository
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.4.1
 
     - name: Terraform init
       id: init
       run: terraform init        

     - name: Terraform format
       id: fmt
       run: terraform fmt
    
     - name: Terraform validate
       id: validate
       run: terraform validate
 
     - name: Terraform plan
       id: plan
       run: terraform plan      

      
