name: Terraform with Sentinel

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Authenticate with Terraform Cloud
      - name: Configure Terraform Cloud
        run: |
          echo "credentials \"app.terraform.io\" {
            token = \"${TF_API_TOKEN}\"
          }" > ~/.terraformrc
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change to your target region
          

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Apply with Sentinel enforcement (runs in Terraform Cloud)
      - name: Terraform Apply
        run: terraform apply tfplan
        env:
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
